### ISSUE TITLE
Passare da dataset amministrazione.txt a enti.csv

### ISSUE THREAD

**Issue by fpietrosanti** [hermescenter/monitorapa#19]
Seguito indicazione di @aborruso su https://github.com/hermescenter/monitorapa/issues/16#issuecomment-1032515710 migrare dal dataset di origine amministrazione.txt a enti.csv/tsv di cui https://indicepa.gov.it/ipa-dati/dataset/enti che è quello più manutenuto da dopo il 31 marzo 2021

**Comment by Shamar** [comment]
fixed in 2e48b7f0cb776f055dd1f6de1dbd9cb6ff7f4ead
