### ISSUE TITLE
Raccolta parlano di noi

### ISSUE THREAD

**Issue by Mte90** [hermescenter/monitorapa#25]
A livello di presentazione un elenco di articoli in cui si presenta il progetto é utile.

In questo ticket vediamo di fare un elenco dei migliori (non solo il rilancio della notizia):

* https://bernieri.blogspot.com/2022/05/nel-torbido-si-pesca-meglio-monitorapa.html (fa un analisi dei dati e dei vari siti che hanno in comune lo stesso tracciamento)

**Comment by Shamar** [comment]
Grazie per il suggerimento, ho messo tutto in home page, sia ciò che dicono altri a o di noi, sia ciò che diciamo noi, in modo che ci sia un dialogo aperto e pubblico
