### ISSUE TITLE
Dove sono i risultati?

### ISSUE THREAD

**Issue by vixrt** [hermescenter/monitorapa#26]
Sarà un evidente mio limite, ma dove si possono visualizzare i risultati in un formato leggibile? (human readable, non machine readable)

Grazie

**Comment by Shamar** [comment]
Trovi tutto sul sito: https://privacy.g0v.it/

Nella home page c'è un grosso bottone blu con la scritta in bianco (secondo le specifiche [WCAG 2](https://www.w3.org/WAI/standards-guidelines/wcag/)) "Scarica il Report".

Si tratta di uno zip che contiene i dati che abbiamo raccolto in due formati aperti (TSV e ODS) e uno... diffuso.

Trovi anche un README.txt con la data di inizio delle verifiche e un LICENSE.txt con la licenza di utilizzo.

Hope this helps! ;-)

**Comment by Mte90** [comment]
Duplicato di https://github.com/hermescenter/monitorapa/issues/24

Lui non ha chiesto un foglio di calcolo ma qualcosa di leggibile e comprensibile come un vero report.

**Comment by Shamar** [comment]
Per la verità ad usare i fogli di calcolo di solito sono umani... ;-)

Comunque grafici e report sono in lavorazione.
