### ISSUE TITLE
Non trovo riscontro della proprietà `l` in `window["ga"]`

### ISSUE THREAD

**Issue by nullndr** [hermescenter/monitorapa#31]
https://github.com/hermescenter/monitorapa/blob/253b17733701b146117fab9871496387011282ce/check/google_analytics.js#L14

Eseguendo un check sulla console del browser nella pagina di stackoverflow ho notato che la proprietà `l` non esiste su `window["ga"]`, è forse un typo per la proprietà `L`?

```
>> Object.keys(window["ga"])
<- Array(14) [ "h", "P", "L", "ya", "answer", "create", "remove", "j", "getAll", "N", … ]
0: "h"
1: "P"
2: "L"
3: "ya"
4: "answer"
5: "create"
6: "remove"
7: "j"
8: "getAll"
9: "N"
10: "loaded"
11: "q"
12: "qd"
13: "getByName"
length: 14
<prototype>: Array []
```

Vorrei inoltre proporre un piccolo refactor del codice js per quanto riguarda lo stile e la scelta dell'uso di `var`

**Comment by Shamar** [comment]
aspetta a rifattorizzare il js che dobbiamo rivederlo per altre ragioni.

l'uso di quelle proprietà, che non ci sono sempre, ci è stato suggerito da Arturo Zanellato ed io le ho riscontrate in diverse istanze di GA.

**Comment by nullndr** [comment]
👍🏼

Resto in attesa

**Comment by Shamar** [comment]
@nullndr ho dovuto cambiare proprio quella linea perché a volte quella proprietà è in minuscolo a volte è in maiuscolo. https://github.com/MonitoraPA/monitorapa/commit/62aa446c6eb0cf21ff7d710e37edd9fe1a40ea3a

Non avrei capito il problema se non fosse stato per la questa tua issue: grazie!
